### PR TITLE
Extend service settings with GUI options in HA

### PR DESCRIPTION
**Pull request by nagyrobi**
...and add chunk_size option too

### CODE REVIEW

**Comment by dummylabs** [comment]
@nagyrobi Thanks, this should be handy. Is there a way to edit "Notification service data" parameter so that it's send to the service as yaml dictionary? If this is not possible via UI, this option should be hidden in my opinion. So far this field holds `[object Object]` which is not editable.

**Comment by nagyrobi** [comment]
Added multiline support for that text field so you can enter the parameters on new lines, like a dictionary looks like.
Needs testing which I can't do because I don't use any external notification services.

**Comment by dummylabs** [comment]
Can I ask you to test it with `persistent_notification.create` which is a part of Home Assistant and requires zero configuration? It has a parameter named `title` which can be used for testing. 
The working yaml example: 
```
service: watchman.report
data:
  send_notification: true
  service: persistent_notification.create
  data:
    title: my title
```

**Comment by dummylabs** [comment]
> so you can enter the parameters on new lines, like a dictionary looks like

As far as I can see, Home Assistant transforms user input into a string, not dictionary when you switch from UI to yaml mode.

**Comment by nagyrobi** [comment]
Yes it can only be a string, you'll have to accomodate with that.
Other way is if you have a known list of possible options, those could be listed in a dropdown box and the user would select the appropriate one.

**Comment by nagyrobi** [comment]
> 

> If this is not possible via UI, this option should be hidden in my opinion

This option is hidden from GUI, remains as a yaml-option.

**Pull request merged**
