### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by IainPHay**
Corrected some spelling errors

### CODE REVIEW

**Comment by jtscott** [comment]
Hi @IainPHay do you mind including in our PR a fix for the services card? I don’t want to do another since you’ve got more fixes here.

line 166 should replace “services” with “entities” to fix the services report card on the latest home-assistant release.

**Comment by IainPHay** [comment]
> entities

Sorry for slow reply, sure can do, to clarify

"sensor.watchman_missing_services", "services") to "sensor.watchman_missing_services", "entities
 or
 "sensor.watchman_missing_services", "services") to "sensor.watchman_missing_sentities", "entities
?

**Comment by jtscott** [comment]
Yeah should be:
`state_attr("sensor.watchman_missing_services", "entities")`

**Comment by IainPHay** [comment]
> Yeah should be: `state_attr("sensor.watchman_missing_services", "entities")`

Cheers that's done.

**Pull request merged**
